# Generated by Django 3.1.2 on 2021-01-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_path', models.FilePathField(blank=True, null=True, verbose_name='Путь к CSV-файлу')),
            ],
        ),
        migrations.CreateModel(
            name='TableOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название поля')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='Ширина поля')),
            ],
        ),
    ]
